name: Deploy
on:
  push:
    branches:
     - main
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Deploy
        run: |
          curl -X POST https://api.github.com/repos/${{ secrets.DEPLOY_REPOSITORY }}/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u smallstepman:${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "post"}'
